A test Jupyter notebook, to work out how to store them on Github in a way that the underlying data is still accessible.

In [3]:

import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from scipy.stats import pearsonr, chi2_contingency
np.set_printoptions(suppress=True, precision = 2)

In [4]:
nba = pd.read_csv("https://raw.githubusercontent.com/keenanandrew/su-data-project/main/nba_games.csv")
nba.head(10)

,game_id,year_id,fran_id,opp_fran,game_location,is_playoffs,pts,opp_pts,game_result,forecast,point_diff
0,194611010TRH,1947,Knicks,Huskies,A,0,68,66,W,0.359935,2
1,194611020CHS,1947,Knicks,Stags,A,0,47,63,L,0.368899,-16
2,194611020PRO,1947,Celtics,Steamrollers,A,0,53,59,L,0.359935,-6
3,194611050BOS,1947,Celtics,Stags,H,0,55,57,L,0.620204,-2
4,194611070STB,1947,Knicks,Bombers,A,0,68,63,W,0.339290,5
5,194611090DTF,1947,Celtics,Falcons,A,0,46,69,L,0.386818,-23
6,194611110NYK,1947,Knicks,Stags,H,0,68,78,L,0.629479,-10
7,194611130CHS,1947,Celtics,Stags,A,0,61,71,L,0.291740,-10
8,194611140STB,1947,Celtics,Bombers,A,0,62,64,L,0.313890,-2
9,194611160BOS,1947,Celtics,Huskies,H,0,53,49,W,0.602702,4

Right. Let's try this again.

In [5]:
nba.describe()

,year_id,is_playoffs,pts,opp_pts,forecast,point_diff
count,24359.000000,24359.000000,24359.000000,24359.000000,24359.000000,24359.000000
mean,1986.916581,0.077754,103.384663,102.438154,0.527805,0.946508
std,17.427172,0.267789,14.724792,14.812181,0.213054,13.341020
min,1947.000000,0.000000,43.000000,38.000000,0.024271,-62.000000
25%,1974.000000,0.000000,94.000000,93.000000,0.359191,-8.000000
50%,1988.000000,0.000000,103.000000,102.000000,0.533177,2.000000
75%,2002.000000,0.000000,113.000000,112.000000,0.698763,10.000000
max,2015.000000,1.000000,173.000000,176.000000,0.976221,56.000000

In [6]:
nba.dtypes

game_id           object
year_id            int64
fran_id           object
opp_fran          object
game_location     object
is_playoffs        int64
pts                int64
opp_pts            int64
game_result       object
forecast         float64
point_diff         int64
dtype: object

In [24]:
# sns.scatterplot(nba, x='pts', y = 'fran_id')

nba.fran_id.unique()

knicks_pts = nba.pts[nba.fran_id == 'Knicks']

knicks_avg = knicks_pts.mean()

print(knicks_avg)

100.97018547408562

In [27]:
nba.head()

nba_2011 = nba[nba.year_id == 2011]

print(nba_2011)

            game_id  year_id  fran_id   opp_fran game_location  is_playoffs  \
22167  201010260BOS     2011  Celtics       Heat             H            0
22168  201010270CLE     2011  Celtics  Cavaliers             A            0
22169  201010270NJN     2011     Nets    Pistons             H            0
22170  201010270OKC     2011  Thunder      Bulls             H            0
22171  201010270SAS     2011    Spurs     Pacers             H            0
...             ...      ...      ...        ...           ...          ...
22608  201105170DAL     2011  Thunder  Mavericks             A            1
22609  201105190DAL     2011  Thunder  Mavericks             A            1
22610  201105210OKC     2011  Thunder  Mavericks             H            1
22611  201105230OKC     2011  Thunder  Mavericks             H            1
22612  201105250DAL     2011  Thunder  Mavericks             A            1

       pts  opp_pts game_result  forecast  point_diff
22167   88       80           W  0.735582           8
22168   87       95           L  0.384577          -8
22169  101       98           W  0.587040           3
22170  106       95           W  0.739462          11
22171  122      109           W  0.761740          13
...    ...      ...         ...       ...         ...
22608  112      121           L  0.333344          -9
22609  106      100           W  0.318375           6
22610   87       93           L  0.628495          -6
22611  105      112           L  0.599898          -7
22612   96      100           L  0.295381          -4

[446 rows x 11 columns]

In [30]:
nba_2011.describe()

nba_2011_pts_avg = nba_2011.pts.mean()

print(nba_2011_pts_avg)

100.87443946188341